
services:
  qdrant:
    image: qdrant/qdrant:v1.14.1-gpu-nvidia
    container_name: cbt_qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      # PRIVACY: Disabilita usage statistics (non monitoring locale)
      - QDRANT__TELEMETRY_DISABLED=true
      # Configurazioni essenziali
      - QDRANT__SERVICE__ENABLE_CORS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
